name: EcomMVC CI/CD Pipeline

on:
  push:
    branches:
      - CiCd-TestRun  # Trigger on push to this branch

jobs:
  build_and_deploy:
    runs-on: windows-latest  # WebDeploy requires Windows environment

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up .NET SDK
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Install EF Core Tools 8.0.10
      - name: Install EF Core Tools 8.0.10
        run: dotnet tool install --global dotnet-ef --version 8.0.10

      # Verify dotnet-ef version
      - name: Verify dotnet-ef version
        run: dotnet ef --version

      # Restore dependencies
      - name: Install dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Publish the project
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --runtime win-x86

      # Optional: Run tests
      - name: Test with .NET
        run: dotnet test

      # Deploy to MonsterASP.NET via WebDeploy
      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.MONSTERASP_MONSTERASP_FTP_WEBSITENAME }}  # Site name from MonsterASP
          server-computer-name: ${{ secrets.MONSTERASP_FTP_SERVERNAME }}  # WebDeploy server URL
          server-username: ${{ secrets.MONSTERASP_FTP_LOGIN_USER }}  # WebDeploy username
          server-password: ${{ secrets.MONSTERASP_FTP_PW }}  # WebDeploy password
          folder: ./publish  # Folder containing the published files