name: Build, publish and deploy to MonsterASP.NET

on:
  push:
    branches:
      - CiCd-TestRun  # Trigger on push to this branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Use Ubuntu (Linux) environment

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up .NET SDK
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Install EF Core Tools 8.0.10
      - name: Install EF Core Tools 8.0.10
        run: dotnet tool install --global dotnet-ef --version 8.0.10

      # Verify dotnet-ef version
      - name: Verify dotnet-ef version
        run: dotnet ef --version

      # Restore dependencies
      - name: Install dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Publish the project
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --runtime linux-x64  # Change runtime to linux-x64

      # Optional: Run tests
      - name: Test with .NET
        run: dotnet test

      # Deploy to MonsterASP.NET via FTP
      - name: Deploy to MonsterASP.NET via FTP
        uses: appleboy/ftp-action@v1.0.0  # FTP action for Linux
        with:
          host: ${{ secrets.MONSTERASP_FTP_SERVERNAME }}  # FTP server name
          username: ${{ secrets.MONSTERASP_FTP_LOGIN_USER }}  # FTP username
          password: ${{ secrets.MONSTERASP_FTP_PW }}  # FTP password
          source: ./publish  # Folder containing the published files
          target: /wwwroot  # Deploy to the root of the website
